### ISSUE TITLE
Unable to view tSQLt results in Jenkins

### ISSUE THREAD

**Issue by jalbador** [jenkinsci/redgate-sql-ci-plugin#11]
Unable to view tSQLt results in Jenkins without going to the jenkins host machine. Is there a way to update the plugin to allow you to view the results within the Jenkins UI.

In the link below it mentions TeamCity and TFS. Could this get added to Jenkins?
 http://documentation.red-gate.com/pages/viewpage.action?pageId=36176681

**Comment by stesieber** [comment]
Add the following post build action:
![image](https://cloud.githubusercontent.com/assets/1697678/25178502/499e43d4-2506-11e7-8b3d-d543647b0068.png)

**Comment by jalbador** [comment]
Thanks. Ill try that out

**Comment by jalbador** [comment]
The solution provided works.
