### ISSUE TITLE
We use redgate version control with subversion is there a plugin for that?

### ISSUE THREAD

**Issue by necroscope** [jenkinsci/redgate-sql-ci-plugin#7]
Hi,

Thanks for all your great work. We use redgate version control with subversion is there a plugin for that? This seems this only works with CVS.  I am I correct?  Thanks again.

Best Regards,

Daniel

**Comment by PeterGerrard** [comment]
Hi Daniel,

Only just seen your comment. This plugin doesn't care about which version control you use, you just need to choose the correct VCS when setting up your build configuration.

**Comment by PeterGerrard** [comment]
Not heard anything will close this
